services:
  postgres:
    image: postgres:16-alpine
    container_name: rms-postgres
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: thrivelab_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d thrivelab_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rms-network
  redis:
    image: redis:7-alpine
    container_name: rms-redis
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - rms-network

  backend:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
    container_name: rms-backend
    ports:
      - "127.0.0.1:3000:3000"
    environment:
      NODE_ENV: dev
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: thrivelab_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - rms-network
  frontend:
    build:
      context: .
      dockerfile: apps/frontend/Dockerfile
      args:
        VITE_API_URL: http://localhost:3000
    container_name: rms-frontend
    ports:
      - "127.0.0.1:5173:80"
    depends_on:
      - backend
    networks:
      - rms-network
  k6:
    image: grafana/k6
    volumes:
      - ./scripts:/scripts
    networks:
      - rms-network
    profiles:
      - tools
    depends_on:
      - backend
    environment:
      - BASE_URL=http://backend:3000
      - PROVIDER_ID=f12b94ba-3193-45f1-94a2-5e84f7b96ad7
    command: run /scripts/concurrency-booking.k6.js
  migrate:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: migration
    profiles:
      - tools
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: thrivelab_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    networks:
      - rms-network
  migrate-revert:
    build:
      context: .
      dockerfile: apps/backend/Dockerfile
      target: migration
    profiles:
      - tools
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      NODE_ENV: development
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: thrivelab_db
      DB_USERNAME: postgres
      DB_PASSWORD: password
    command: ["pnpm", "--filter", "backend", "migration:revert"]
    networks:
      - rms-network
volumes:
  postgres_data:
  redis_data:
  localstack_data:

networks:
  rms-network:
    driver: bridge
